version: 2

sources:
  - name: raw_data
    database: airflow
    schema: public
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: name
            tests:
              - not_null
          - name: email
            tests:
              - not_null
              - unique
          - name: country
            tests:
              - not_null

      - name: orders
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: customer_id
            tests:
              - not_null
          - name: total_amount
            tests:
              - not_null
          - name: status
            tests:
              - accepted_values:
                  arguments:
                    values: ["Pending", "Completed", "Cancelled"]

      - name: order_items
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: order_id
            tests:
              - not_null
          - name: product_id
            tests:
              - not_null
          - name: quantity
            tests:
              - not_null
          - name: unit_price
            tests:
              - not_null

      - name: products
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: name
            tests:
              - not_null
          - name: price
            tests:
              - not_null
          - name: category
            tests:
              - not_null
